common/urls.py
from django.urls import path

from common.views import HomeView, VoteView

app_name = 'common'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('vote', VoteView.as_view(), name='vote'),
]

rediti/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('users.urls')),
    path('', include('subs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subs/urls.py
from django.urls import path
from subs.views import SubreditisListView, SubreditiDetailView, ThreadDetailView, CreateThreadView, CreatePostView, DeletePostView, SubscribeView

app_name = 'subs'

urlpatterns = [
    path('subs/', SubreditisListView.as_view(), name='subreditis'),
    path('subs/<slug:slug>/', SubreditiDetailView.as_view(), name='subrediti'),
    path('thread/<int:pk>/', ThreadDetailView.as_view(), name='thread'),
    path('thread/new/', CreateThreadView.as_view(), name='create_thread'),
    path('post/new/', CreatePostView.as_view(), name='create_post'),
    path('post/delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
    path('subscribe', SubscribeView.as_view(), name='subscribe'),
]

users/urls.py
from django.urls import path

from .views import LogoutView, LoginView, SignupView, ProfileView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

subs/models.py
from django.db import models
from common.models import IndexedTimeStampedModel

class Subrediti(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    creator = models.ForeignKey('users.User', related_name="subreditis", on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Thread(IndexedTimeStampedModel):
    title = models.CharField(max_length=50)
    author = models.ForeignKey('users.User', related_name="threads", on_delete=models.CASCADE)
    subrediti = models.ForeignKey('Subrediti', related_name="threads", on_delete=models.CASCADE)
    vote_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title


class Post(IndexedTimeStampedModel):
    content = models.TextField()
    author = models.ForeignKey('users.User', related_name="posts", on_delete=models.CASCADE)
    thread = models.ForeignKey('Thread', related_name="posts", on_delete=models.CASCADE)
    vote_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return ("{} - {} - {}").format(self.id, self.thread, self.author)


class Subscription(models.Model):
    subrediti = models.ForeignKey('Subrediti', on_delete=models.CASCADE)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE)
    subscribed = models.BooleanField(default=False)

    class Meta:
        unique_together = [('subrediti', 'user')]

    def __str__(self):
        return ("{} - {}").format(self.subrediti, self.user)

subs/forms.py
from django import forms
from .models import Thread, Post

class CreateThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        field = forms.CharField()
        self.fields['post'] = field

    def save(self, commit=True):
        post_content = self.cleaned_data['post']
        self.instance.subrediti_id = self.initial['subrediti'].id
        self.instance.author = self.initial['author']
        self.instance.save()
        Post.objects.create(
            content=post_content,
            author=self.initial['author'],
            thread = self.instance,
        )
        return super().save()


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']

    def save(self, commit=True):
        self.instance.thread = self.initial['thread']
        self.instance.author = self.initial['author']
        self.instance.save()
        return super().save()

subs/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from .models import Subrediti, Thread, Post, Subscription
from .forms import CreateThreadForm, CreatePostForm
from .helpers import subscribe_or_unsubscribe

class SubreditisListView(generic.ListView):
    template_name = 'subs/subreditis.html'
    model = Subrediti
    context_object_name = 'subreditis'


class SubreditiDetailView(generic.DetailView):
    template_name = 'subs/subrediti.html'
    model = Subrediti

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subscription, created = Subscription.objects.get_or_create(user=self.request.user, subrediti=self.object)
        context['subscribed'] = True if subscription.subscribed else False
        return context


class ThreadDetailView(generic.DetailView):
    template_name = 'subs/thread.html'
    model = Thread


class CreateThreadView(generic.CreateView):
    template_name = 'subs/create_thread.html'
    model = Thread
    form_class = CreateThreadForm

    def get_initial(self):
        self.subrediti = self.request.GET.get('sub', None)
        return {
            'subrediti': Subrediti.objects.get(id=self.subrediti),
            'author': self.request.user,
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subrediti'] = Subrediti.objects.get(id=self.subrediti)
        return context

    def get_success_url(self):
        subrediti = Subrediti.objects.get(id=self.subrediti)
        return reverse('subs:subrediti', kwargs={'slug': subrediti.slug})


class CreatePostView(generic.CreateView):
    template_name = 'subs/create_post.html'
    model = Post
    form_class = CreatePostForm

    def get_initial(self):
        self.thread = self.request.GET.get('thread', None)
        return {
            'thread': Thread.objects.get(id=self.thread),
            'author': self.request.user,
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['thread'] = Thread.objects.get(id=self.thread)
        return context

    def get_success_url(self):
        thread = Thread.objects.get(id=self.thread)
        return reverse('subs:thread', kwargs={'pk': thread.pk})


class DeletePostView(generic.DeleteView):
    model = Post
    template_name = 'subs/post_confirm_delete.html'
    success_url = 'home'


class SubscribeView(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        self.subrediti = self.request.GET.get('sub', None)
        subscribe_or_unsubscribe(self.subrediti, self.request.user)
        return self.request.META.get('HTTP_REFERER')

templates/subs/create_post.html
{% extends 'base.html' %}
{% block body %}
<a href="{% url 'subs:thread' thread.id %}">Back to {{ thread.title }}</a>
<h3>Creating thread in {{ thread.title }}</h3>
{% if form.errors %}
{{ form.non_field_errors }}
{{ form.errors.name }}
{% endif %}
<form class="post-form" method="POST">
{% csrf_token %}
<label>Conteúdo do post</label>
<textarea type="text" name="content" placeholder="Escreva aqui"></textarea>
<input type="submit" value="Create">
</form>
{% endblock %}

templates/subs/create_thread.html
{% extends 'base.html' %}
{% block body %}
<a href="{% url 'subs:subrediti' subrediti.slug %}">Back to {{ subrediti.title }}</a>
<h3>Creating thread in {{ subrediti.title }}</h3>
{% if form.errors %}
{{ form.non_field_errors }}
{{ form.errors.name }}
{% endif %}
<form class="post-form" method="POST">
{% csrf_token %}
<label>Thread name</label>
<input type="text" name="title" placeholder="Name your thread">
<label>Content</label>
<textarea type="text" name="post" placeholder="Write your initial post"></textarea>
<input type="submit" value="Create">
</form>
{% endblock %}

templates/subs/post_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

templates/subs/subrediti.html
{% extends 'base.html' %}
{% block body %}
<h1 class="main-title">{{ subrediti.title }}</h1>
<a href="{% url 'subs:create_thread' %}?sub={{ subrediti.id }}">Nova thread</a>
<a href="{% url 'subs:subscribe' %}?sub={{ subrediti.id }}">
    {% if subscribed %}
        Desinscrever-se
    {% else %}
        Inscrever-se
    {% endif %}
</a>

<div class="forum-container">
    <div class="subrediti-list">
        {% for thread in subrediti.threads.all %}
        <div class="subrediti-card">
            <h4>
                <a href="{% url 'subs:thread' thread.pk %}">
                    {{ thread.title }}
                </a> 
                by <a href="{% url 'users:profile' thread.author.pk %}">
                    {{ thread.author }}
                </a> at {{ thread.created }}
            </h4>
            <div class="karma-button">
                {{ thread.vote_count }}<br>
                <a href="{% url 'common:vote' %}?target_type=thread&target_id={{ thread.id }}"><button>↑</button></a>
            </div>
        </div>
        {% empty %}
        Awww, ninguém criou uma thread :(
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/subs/subreditis.html
{% extends 'base.html' %}
{% block body %}
<h1 class="main-title">Subreditis</h1>
<div class="forum-container">
    <div class="subrediti-list">
        {% for subrediti in subreditis %}
        <div class="subrediti-card">
            <div>
                <h4><a href="{% url 'subs:subrediti' subrediti.slug %}">{{ subrediti.title }}</a></h4>
                <div>{{ subrediti.description }}</div>
            </div>
        </div>
        {% empty %}
        Awww, ninguém criou nenhum subrediti :(
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/subs/thread.html
{% extends 'base.html' %}
{% block body %}
<h1 class="main-title">{{ thread.title }}</h1>
<a href="{% url 'subs:create_post' %}?thread={{ thread.id }}">Novo post</a>
<div class="forum-container">
    <div class="subrediti-list">
        {% for post in thread.posts.all %}
        <div class="subrediti-card">
            <div>
                <a href="{% url 'users:profile' thread.author.pk %}">
                    {{ post.author }}
                </a> at {{ post.created }}
                <div>
                    {{ post.content }}
                </div>
                {% if request.user.id == post.author.id %}
                <a href="{% url 'subs:delete_post' post.pk %}">Delete post</a>
                {% endif %}
            </div>
            <div class="karma-button">
                <div>{{ post.vote_count }}</div>
                <a href="{% url 'common:vote' %}?target_type=post&target_id={{ post.id }}"><button>↑</button></a><br>
            </div>
        </div>
        {% empty %}
        Awww, ninguém postou ainda :(
        {% endfor %}
    </div>
</div>
{% endblock %}