rediti/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('users.urls')),
    path('', include('subs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subs/urls.py
from django.urls import path
from subs.views import SubreditisListView, SubreditiDetailView, ThreadDetailView, CreateThreadView, CreatePostView, DeletePostView, SubscribeView

app_name = 'subs'

urlpatterns = [
    path('subs/', SubreditisListView.as_view(), name='subreditis'),
    path('subs/<slug:slug>/', SubreditiDetailView.as_view(), name='subrediti'),
    path('thread/<int:pk>/', ThreadDetailView.as_view(), name='thread'),
    path('thread/new/', CreateThreadView.as_view(), name='create_thread'),
    path('post/new/', CreatePostView.as_view(), name='create_post'),
    path('post/delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
    path('subscribe', SubscribeView.as_view(), name='subscribe'),
]

users/urls.py
from django.urls import path

from .views import LogoutView, LoginView, SignupView, ProfileView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

templates/base.html
{% load static %}
<html>

<head>
  <title>Rediti</title>
  <link rel="shortcut icon" type="image/png" href="http://i.imgur.com/sdO8tAw.png"/>
  <link href="{% static 'style.css' %}" rel="stylesheet">
</head>

<body>
  {% include 'navbar.html' %}
  <div class="container">
    {% block body %}{% endblock %}
  </div>
  <footer>
    <span>Rediti feito nas férias de alto impacto de 2019.1</span>
  </footer>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="home">
    <div class="list-container">
        <h1>/home</h1>
        {% if user.is_authenticated %}
            {% if subscriptions %}
                {% for sub in subscriptions %}
                    {% if sub.subrediti.threads.first and sub.subscribed == True %}
                    <div class="list-thread">
                        <span>{{ sub.subrediti.title }}</span>
                        <a href="{% url 'subs:thread' sub.subrediti.threads.first.pk %}">{{ sub.subrediti.threads.first }}</a>
                        by <a href="{% url 'users:profile' sub.subrediti.threads.first.author.id %}">{{ sub.subrediti.threads.first.author }}</a>
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                You don't have any subscriptions yet.
            {% endif %}
        {% else %}
            {% for subrediti in subreditis %}
                {% if subrediti.threads.first %}
                <div class="list-thread">
                    <span>{{ subrediti.title }}</span>
                    <a href="{% url 'subs:thread' subrediti.threads.first.pk %}">{{ subrediti.threads.first }}</a>
                    by <a href="{% url 'users:profile' subrediti.threads.first.author.id %}">{{ subrediti.threads.first.author }}</a>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    <div class="new-subs">
        <h1>/new subreditis</h1>
        {% for new_sub in subreditis %}
        <li><a href="{% url 'subs:subrediti' new_sub.pk %}">{{ new_sub.title }}</a></li>
        {% empty %}
        No new subreditis
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/navbar.html
<div class="navbar">
    <div><a href="/"><img class="site-logo" src="https://logodownload.org/wp-content/uploads/2018/02/reddit-logo.png"></a></div>
    <div class="nav-links">
        <a class="nav-link" href="/">Início</a> |
        {% if user.is_authenticated %}
            <a class="nav-link" href="">Novo subrediti</a> |
            <a class="nav-link" href="{% url 'subs:subreditis' %}">Subreditis</a> |
            <a class="nav-link" href="{% url 'users:profile' user.pk %}">{{ user.username }} ({{ user.karma }})</a> |
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        {% else %}
            <a class="nav-link" href="{% url 'users:signup' %}">Cadastro</a> |
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </div>
</div>